"""
    Relevant port serial numbers involved
"""

EDGE_NODE_LOAD_UPDATE_PORT = 8997

EDGE_NODE_CPU_UPDATE_PORT = 9009

EDGE_NODE_LC_UPDATE_PORT = 9012

EDGE_NODE_LC_WORK_PORT = 9015

LC_RESULT_PORT = 8994
