"""
    Relevant port serial numbers involved
"""

LC_NODE_DECISION_PORT = 9000

BE_NODE_DECISION_PORT = 9013

CLOUD_NODE_LC_DISTRIBUTE_PORT = 9015

CLOUD_REQ_RES_UPDATE_PORT = 8996

VIRTUAL_REQ_PORT = 9100